### ISSUE TITLE
How can I use this on MacOSX?

### ISSUE THREAD

**Issue by sergueif** [nichobi/beets-yapl#1]
The readme seems to suggest this is an arch-linux available thing right now, right?

I'd love to use this too. I've even written my own scripts writing playlists as plain-text artist - title CSVs and then having code look up the "path" to the actual files and spit that out as a `.m3u`. So I feel the pain this repo is trying to address :)

**Comment by nichobi** [comment]
Ideally, I would have published this on PyPi so you could install it with `pip install --user beets-yapl`, but I haven't had the time to figure that out yet. Hopefully I'll fix it soon.

For now, you could clone this repo onto your python path. The exact location for this seems to vary by [operating system](https://docs.python.org/2/library/site.html#site.USER_SITE), but seems to either be `~/.local/lib/pythonX.Y/site-packages` or `~/Library/Python/X.Y/lib/python/site-packages` on Mac.

**Comment by sergueif** [comment]
Hey thanks, I ended up moving my beets instance to a linux raspberry pi closer to the music drive, but this might still come in handy for myself or some other Mac users. Excited to try this plugin

Cheers, thank you!

**Comment by sergueif** [comment]
Hey I cloned it into `site-packages` like
```
me@machine:~/.local/lib/python3.9/site-packages/beets-yapl $ ls
LICENSE  README.md  beetsplug  setup.py
```

but `beet yaml` still gives me a bunch of errors like:
```
rpi3@rpi3omv:~/.local/lib/python3.9/site-packages/beets-yapl $ beet yapl
** error loading plugin yapl:
Traceback (most recent call last):
  File "/home/rpi3/.local/lib/python3.9/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.yapl'

error: unknown command 'yapl'
```
or
```
** error loading plugin yapl:
Traceback (most recent call last):
  File "/home/rpi3/.local/lib/python3.9/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
  File "/home/rpi3/.local/lib/python3.9/site-packages/beetsplug/yapl.py", line 49
    match len(results):
          ^
SyntaxError: invalid syntax

error: unknown command 'yapl'
```
when I moved `beetsplug` folder into `site-packages`

**Comment by nichobi** [comment]
Ah, looks like  I got the location slightly wrong then, the second one is correct. 

The issue you're getting there is because the `match` statement was added in Python 3.10 and you're running Python 3.9. You could perhaps upgrade your python version, but I'll also look into replacing those lines with something more backwards-compatible.

**Comment by nichobi** [comment]
> I'll also look into replacing those lines with something more backwards-compatible.

Just pushed a commit that to make it compatible with 3.9, so if you pull in the new changes and put it in the right place again, it should hopefully work

**Comment by sergueif** [comment]
Hey thanks, to get python3.10, I'd have to install it from source on my raspberry pi 3, which is no fun. 

with some mucking around, it kinda worked. It still spewed errors at me, but oddly-enough did write the `workout.m3u` playlist:
```
rpi3@rpi3omv:~/.local/lib/python3.9/site-packages $ mv beets-yapl/beetsplug ./
rpi3@rpi3omv:~/.local/lib/python3.9/site-packages $ beet yapl
** error loading plugin discogs:
Traceback (most recent call last):
  File "/home/rpi3/.local/lib/python3.9/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.discogs'

** error loading plugin smartplaylist:
Traceback (most recent call last):
  File "/home/rpi3/.local/lib/python3.9/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.smartplaylist'

** error loading plugin edit:
Traceback (most recent call last):
  File "/home/rpi3/.local/lib/python3.9/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.edit'

Parsing workout.yaml
Writing workout.m3u
```

🤷

**Comment by sergueif** [comment]
oh, dang, I think it made your plugin work, but it broke my other ones :)

**Comment by nichobi** [comment]
Oops, you probably deleted the whole beetsplug folder from sitepackages, which included your other plugins as well. An easy mistake to make and all the more reason for me to fix `pip` installation, so others won't do the same!

**Comment by sergueif** [comment]
I sure did. :) do you happen to know how to bring it back? I guess I'll re-install `beets`

**Comment by nichobi** [comment]
Yeah, reinstalling beets should do it. You should be able to force a reinstall with `pip install --user --ignore-installed beets`

**Comment by sergueif** [comment]
I fixed `beets` and did `cp beets-yapl/beetsplug/yapl.py .local/lib/python3.9/site-packages/beetsplug/` and now everything + `yapl` works. Yay I can make my very nice playlists.

**Comment by nichobi** [comment]
Hooray! Do let me know if you have any other issues or feature requests :)

**Comment by nichobi** [comment]
Turned out I was just missing something silly with PyPI. It's now installable via `pip install beets-yapl`!
